### ISSUE TITLE
refresh does not refresh missing resources in state file

### ISSUE THREAD

**Issue by angrox** [profitbricks/terraform-provider-profitbricks#33]
After deleting resources in the Profitbricks DCD terraform cannot refresh the changes to the tfstate file. It breaks with an error that the resources do not exist anymore:

```
# terraform refresh

[...]

Error refreshing state: 3 error(s) occurred:

* profitbricks_volume.test-instance-datadisk.1: An error occured while fetching a volume ID ac3cff59-946e-4639-b57f-75d7bcf8996e {
  "httpStatus" : 404,
  "messages" : [ {
    "errorCode" : "309",
    "message" : "Resource does not exist"
  } ]
}

* profitbricks_volume.test-instance-datadisk.0: An error occured while fetching a volume ID c98686cf-9ed8-4a99-aecb-94e9658b283f {
  "httpStatus" : 404,
  "messages" : [ {
    "errorCode" : "309",
    "message" : "Resource does not exist"
  } ]
}

* profitbricks_volume.test-instance-datadisk.2: An error occured while fetching a volume ID 5f503b44-7fdd-44c8-8179-55a58633e2c4 {
  "httpStatus" : 404,
  "messages" : [ {
    "errorCode" : "309",
    "message" : "Resource does not exist"
  } ]
}
```

terraform 0.8.8
profitbricks-provider 1.2.1

**Comment by jasminSPC** [comment]
The way how Terrafrom is designed this isn't a bug. 

`tfstate` is a file where Terraform stores information about infrastructure it provisions. So for example if you rename a ProfitBricks volume from DCD and do `terrafrom refresh` Terrraform will sync that data with tfstate, but in case the resource has been removed Terraform will try to fetch that object by its identifier and fail because the resource doesn't exist anymore. 

To work around this scenario you can use Terraform's [taint](https://www.terraform.io/docs/commands/taint.html) parameter or you can manually remove non-existent resources from `tfstate`.

**Comment by jasminSPC** [comment]
I'm sorry for the previous message. I checked with hashicorp team and they told me that there is a way to handle that. 

I will keep you posted once we have a fix for that. 
I'm sorry for inconvenience

**Comment by jasminSPC** [comment]
[Here](https://github.com/profitbricks/terraform-provider-profitbricks/releases/tag/v1.2.2) is the fix
