### ISSUE TITLE
Basic Example - Error

### ISSUE THREAD

**Issue by japita-se** [profitbricks/terraform-provider-profitbricks#35]
Very simple conf does not work.
	
             data "profitbricks_location" "loc" {
		  name = "de/fra"
		  feature = "SSD"
		}
		# Provider
		provider "profitbricks"  {
		  username =  
		  password =  
		  endpoint =  "https://api.profitbricks.com/rest/v3/"
		  retries = "10"  
		}
		# Details of Provider
		resource "profitbricks_datacenter" "main" {  
		  location = "${data.profitbricks_location.loc.id}"
		  description = "datacenter description"
		  "name"      = "Data Center Evolvere"  
		}
terraform apply 

		Error refreshing state: 1 error(s) occurred:

		* data.profitbricks_location.loc: 1 error(s) occurred:

		* data.profitbricks_location.loc: data.profitbricks_location.loc: An error occured while fetching ProfitBricks locations {
		  "httpStatus" : 404,
		  "messages" : [ {
		    "errorCode" : "309",
		    "message" : "Resource does not exist"
		  } ]
		}

**Comment by jasminSPC** [comment]
The endpoint you are using is incorrect https://api.profitbricks.com/rest/v3/ try replacing it with
**https://api.profitbricks.com/cloudapi/v3**

**Comment by japita-se** [comment]
OK, you are right. But also the location name seems to be wrong:
```
data "profitbricks_location" "loc" {
  name = "fra"  
  feature = "SSD"
}
# Provider
provider "profitbricks"  {
  username = "..."
  password = "..."
  endpoint =  "https://api.profitbricks.com/cloudapi/v3"
  retries = "10"   

}
```

**Comment by jasminSPC** [comment]
This is how location object looks:
```{
    "id" : "de/fkb",
    "type" : "location",
    "href" : "https://api.profitbricks.com/cloudapi/v3/locations/de/fkb",
    "properties" : {
      "name" : "karlsruhe",
      "features" : [ "SSD", "MULTIPLE_CPU" ]
    }
  }```

`location` data source is searching by location name or part of the name, or by features. If you are searching by locations ID like `us/las` you already know location ID so it defeats the purpose.  

Also the number of retries is not going to be enough. To provision a servers, depending on the size, it can take up to 2 minutes to provision. I would recommend you leave out retries since the default value is **50**.  Also default endpoint has default value so there is no need to override it. The latest build will only work with latest CloudAPI version.

**Comment by japita-se** [comment]
Thank you,. I just followed the example in the doc 
https://github.com/profitbricks/terraform-provider-profitbricks#credentials
